/**
@abstract {string} name 
@virtual {string} name
@access {string} name
@alias {string} name
@async {string} name
@augments {string} name 
@extends {string} name
@author {string} name
@borrows {string} name
@callback {string} name
@class {string} name 
@constructor {string} name
@classdesc {string} name
@constant {string} name
@const {string} name
@constructs {string} name
@copyright {string} name
@default {string} name 
@defaultvalue {string} name
@deprecated {string} name
@description {string} name 
@desc {string} name
@enum {string} name
@event {string} name
@example {string} name
@exports {string} name
@external {string} name 
@host {string} name
@file {string} name 
@fileoverview {string} name
@overview {string} name
@fires {string} name 
@emits {string} name
@function {string} name 
@func {string} name
@method {string} name
@generator {string} name
@global {string} name
@hideconstructor {string} name
@ignore {string} name
@implements {string} name
@inheritdoc {string} name
@inner {string} name
@instance {string} name
@interface {string} name
@kind {string} name
@lends {string} name
@license {string} name
@listens {string} name
@member {string} name 
@var {string} name
@memberof {string} name
@mixes {string} name
@mixin {string} name
@module {string} name
@name {string} name
@namespace {string} name
@override {string} name
@package {string} name
@param {string} name 
@arg {string} name
@argument {string} name
@private {string} name
@property {string} name 
@prop {string} name
@protected {string} name
@public {string} name
@readonly {string} name
@requires {string} name
@returns {string} name 
@return {string} name
@see {string} name
@since {string} name
@static {string} name
@summary {string} name
@this {string} name
@throws {string} name 
@exception {string} name
@todo {string} name
@tutorial {string} name
@type {string} name
@typedef {string} name
@variation {string} name
@version {string} name
@yields {string} name 
@yield {string} name
*/
